name: React App CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: |
          cd react-app
          npm ci
      - name: Run linter
        run: |
          cd react-app
          npm run lint || npm run lint:fix || exit 1
      - name: Run tests
        run: |
          cd react-app
          npm test -- --watchAll=false
